name: Project Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run project tests
      run: |
        chmod +x project/tests.sh
        ./project/tests.sh